name: CI
on: [push, workflow_dispatch]
permissions:
  actions: none
  checks: none
  contents: none
  deployments: none
  discussions: none
  id-token: none
  issues: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
          submodules: true
      - name: Install dependencies
        run: ./deps.sh
      - name: Make PoCs
        run: ./make.sh
      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        with:
          name: pocs
          path: |
            poc*.apk
